name: network
description: Package including hooks for easy works with http package in dart
version: 1.0.0
homepage: https://github.com/ScerIO/packages.dart/tree/master/packages/network

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: 3.19.1

dependencies:
  http: ^1.1.0

dev_dependencies:
  test: ^1.21.1
