name: extension
description: Package including lot helpers for easy developing on dart language
version: 0.6.0
homepage: https://github.com/ScerIO/packages.dart/tree/master/packages/extension

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: 3.19.1

dependencies:
  meta: ^1.8.0

dev_dependencies:
  test: ^1.21.1
